# generated by datamodel-codegen:
#   filename:  openapi.json

from __future__ import annotations

from typing import Any, Literal, TypedDict

from typing_extensions import NotRequired


class CiSettings(TypedDict):
    pass_rate_floor: NotRequired[float | None]
    max_concurrency: NotRequired[int | None]
    default_pass_rate: NotRequired[float | None]


class ContextReport(TypedDict):
    seeds: dict[str, Any]
    probing: list[dict[str, Any]]
    user_models: list[dict[str, Any]]
    representations: list[dict[str, Any]]
    tests: dict[str, Any]
    assessment: list[dict[str, Any]]


class Dataset(TypedDict):
    id: str
    generation_id: str
    user_model_id: str
    row_count: int


class DatasetList(TypedDict):
    data: list[Dataset]


class DatasetRow(TypedDict):
    scenario_id: str
    task_family: str
    controls: dict[str, Any]
    spec: dict[str, Any]
    random_seed: NotRequired[int | None]


class DatasetRows(TypedDict):
    data: list[DatasetRow]


class DemoAgent(TypedDict):
    id: str
    name: str


class DemoAgentCreate(TypedDict):
    name: str
    url: str
    key: NotRequired[str | None]


class DemoAgentList(TypedDict):
    data: list[DemoAgent]


class DemoSessionCreate(TypedDict):
    context: str


class DemoSimulationCreate(TypedDict):
    scenario_id: str
    agent_system_prompt: NotRequired[str | None]
    agent_id: NotRequired[str | None]


class DemoTrace(TypedDict):
    scenario_id: str
    task_family: str
    controls: dict[str, Any]
    spec: dict[str, Any]
    badges: list[dict[str, Any]]
    ladder: NotRequired[str | None]


class Event(TypedDict):
    seq: int
    id: str
    stage: str
    message: str
    data: NotRequired[dict[str, Any]]
    created_at: str


class EventList(TypedDict):
    data: list[Event]


class GenerationCreate(TypedDict):
    user_model_id: str
    count: NotRequired[int]
    quality_check_id: NotRequired[str | None]


class GenerationJob(TypedDict):
    id: str
    status: Literal['running', 'succeeded', 'failed']
    user_model_id: str
    count: int
    dataset_id: NotRequired[str | None]
    error: NotRequired[str | None]


class HealthResponse(TypedDict):
    status: str
    version: str
    sha: NotRequired[str | None]


class MetricDefinition(TypedDict):
    name: str
    label: str
    unit: Literal['count', 'percent', 'ms']
    description: str


class MetricDefinitionList(TypedDict):
    data: list[MetricDefinition]


class MetricPoint(TypedDict):
    t: str
    v: float


class MetricSummary(TypedDict):
    name: str
    value: float
    previous: NotRequired[float | None]
    series: NotRequired[list[MetricPoint]]


class ProbeSession(TypedDict):
    id: str
    status: Literal['active', 'converged']
    turn: int
    max_turns: int
    next_probe: NotRequired[str | None]
    user_model_id: NotRequired[str | None]
    seed_ids: NotRequired[list[str]]


class ProbeSessionCreate(TypedDict):
    max_turns: NotRequired[int]
    seed_ids: NotRequired[list[str]]


class QualityCheck(TypedDict):
    id: str
    status: Literal['running', 'succeeded', 'failed']
    rollout_ids: list[str]
    label: NotRequired[str | None]
    error: NotRequired[str | None]


class QualityCheckCreate(TypedDict):
    rollout_ids: list[str]
    label: NotRequired[str | None]


class QualityCheckSummary(TypedDict):
    id: NotRequired[str | None]
    passed: NotRequired[int]
    total: NotRequired[int]


class RequestLogItem(TypedDict):
    route: str
    method: str
    status: int
    api_key_id: NotRequired[str | None]
    latency_ms: float
    created_at: str


class RequestLogList(TypedDict):
    data: list[RequestLogItem]


class RolloutCreate(TypedDict):
    scenario_id: str
    random_seed: NotRequired[int | None]
    max_turns: NotRequired[int]
    agent: NotRequired[dict[str, Any] | None]
    dataset_id: NotRequired[str | None]


class RolloutDetail(TypedDict):
    id: str
    status: str
    scenario_id: str
    agent: NotRequired[dict[str, Any] | None]
    dataset_id: NotRequired[str | None]
    end_reason: NotRequired[str | None]
    events: NotRequired[list[Event]]
    task_family: NotRequired[str | None]
    controls: NotRequired[dict[str, Any]]
    spec: NotRequired[dict[str, Any]]
    created_at: str
    completed_at: NotRequired[str | None]
    random_seed: int
    simulator_config: NotRequired[dict[str, Any]]
    hidden_state: NotRequired[dict[str, Any]]
    env_snapshot: NotRequired[dict[str, Any]]
    turns: NotRequired[list[dict[str, Any]]]
    tool_events: NotRequired[list[dict[str, Any]]]
    evaluations: NotRequired[list[dict[str, Any]]]


class RolloutEvaluation(TypedDict):
    rollout_id: str
    passed: bool
    states: list[dict[str, Any]]
    judge: dict[str, Any]


class RolloutEvaluationList(TypedDict):
    data: list[RolloutEvaluation]


class RunDetail(TypedDict):
    id: str
    type: Literal['generation', 'validation_run', 'quality_check', 'voice_render']
    status: str
    sdk_session_id: NotRequired[str | None]
    sdk_session_name: NotRequired[str | None]
    created_at: str
    completed_at: NotRequired[str | None]
    error: NotRequired[str | None]
    summary: NotRequired[dict[str, Any]]
    detail: NotRequired[dict[str, Any]]
    events: NotRequired[list[Event]]


class RunSummary(TypedDict):
    id: str
    type: Literal['generation', 'validation_run', 'quality_check', 'voice_render']
    status: str
    sdk_session_id: NotRequired[str | None]
    sdk_session_name: NotRequired[str | None]
    created_at: str
    completed_at: NotRequired[str | None]
    error: NotRequired[str | None]
    summary: NotRequired[dict[str, Any]]


class SandboxConfig(TypedDict):
    seed: int
    fail_tools: NotRequired[list[str]]
    state: NotRequired[dict[str, Any]]


class ScenarioValidation(TypedDict):
    scenario_id: str
    passed: bool
    judge: dict[str, Any]


class ScenarioValidationList(TypedDict):
    data: list[ScenarioValidation]


class SdkSession(TypedDict):
    sdk_session_id: str
    sdk_invocation_id: str
    name: str
    voice_enabled: NotRequired[bool]
    voice_auto: NotRequired[bool]
    ci: NotRequired[CiSettings | None]


class SdkSessionCreate(TypedDict):
    name: str
    sdk_version: NotRequired[str | None]
    ci: NotRequired[dict[str, Any] | None]


class SdkSessionSummary(TypedDict):
    id: str
    name: str
    created_at: str
    last_activity: NotRequired[str | None]
    runs: int
    rollouts: int


class Seed(TypedDict):
    id: str
    kind: str
    source: str
    version: str
    chunks: int


class SeedCreate(TypedDict):
    kind: Literal[
        'document', 'tool_schema', 'policy', 'seed_conversation', 'trace', 'db_record'
    ]
    source: str
    content: NotRequired[dict[str, Any]]
    version: NotRequired[str]
    metadata: NotRequired[dict[str, Any]]
    audio_b64: NotRequired[str | None]
    audio_filename: NotRequired[str | None]


class ToolCall(TypedDict):
    name: str
    input: dict[str, Any]
    output: NotRequired[dict[str, Any] | None]
    is_error: NotRequired[bool]
    turn_idx: NotRequired[int | None]
    seq: NotRequired[int | None]
    external: NotRequired[bool]


class TranscriptTurn(TypedDict):
    role: Literal['user', 'agent']
    content: str
    audio_url: NotRequired[str | None]


class UsageSummary(TypedDict):
    range: str
    bucket_seconds: int
    start: str
    metrics: list[MetricSummary]


class UserModel(TypedDict):
    id: str
    probe_session_id: str
    persona: str
    traits: list[str]
    representation_id: NotRequired[str | None]


class UserModelList(TypedDict):
    data: list[UserModel]


class ValidationError(TypedDict):
    loc: list[str | int]
    msg: str
    type: str
    input: NotRequired[Any]
    ctx: NotRequired[dict[str, Any]]


class ValidationRun(TypedDict):
    id: str
    dataset_id: str
    label: NotRequired[str | None]
    status: Literal['running', 'succeeded', 'failed']
    verdict: NotRequired[Literal['pass', 'warn'] | None]
    reference: NotRequired[dict[str, Any] | None]
    validity: NotRequired[dict[str, Any] | None]
    fidelity: NotRequired[dict[str, Any] | None]
    diversity: NotRequired[dict[str, Any] | None]
    error: NotRequired[str | None]


class ValidationRunCreate(TypedDict):
    label: NotRequired[str | None]


class VoiceRender(TypedDict):
    id: str
    status: Literal['running', 'succeeded', 'failed']
    scenario_id: NotRequired[str | None]
    rollout_id: NotRequired[str | None]
    params: NotRequired[dict[str, Any]]
    duration_ms: NotRequired[int | None]
    wpm: NotRequired[float | None]
    provenance: NotRequired[list[dict[str, Any]] | None]
    error: NotRequired[str | None]


class VoiceRenderCreate(TypedDict):
    scenario_id: NotRequired[str | None]
    rollout_id: NotRequired[str | None]
    takes: NotRequired[int]
    stability: NotRequired[float | None]
    phone_fx: NotRequired[bool]
    room_tone: NotRequired[bool]
    annotate: NotRequired[bool]
    voice_overrides: NotRequired[dict[str, str]]


class DemoSession(TypedDict):
    id: str
    status: Literal['running', 'succeeded', 'failed']
    error: NotRequired[str | None]
    phase: NotRequired[
        Literal['reading', 'distilling', 'world_model', 'writing_tests'] | None
    ]
    traces: NotRequired[list[DemoTrace]]


class DemoTierResult(TypedDict):
    rollout_id: str
    transcript: list[TranscriptTurn]
    tool_events: list[ToolCall]
    violations: list[str]
    tool_calls: int
    goals_met: int
    goals_total: int
    conduct: NotRequired[dict[str, Any] | None]
    label: NotRequired[str | None]


class HTTPValidationError(TypedDict):
    detail: NotRequired[list[ValidationError]]


class KeyUsage(TypedDict):
    api_key_id: NotRequired[str | None]
    requests: int
    errors: int
    p95_latency_ms: NotRequired[float | None]
    last_used: NotRequired[str | None]
    series: NotRequired[list[MetricPoint]]


class KeyUsageList(TypedDict):
    data: list[KeyUsage]


class ProbeResponse(TypedDict):
    reply: str
    tool_calls: NotRequired[list[ToolCall]]


class Rollout(TypedDict):
    id: str
    scenario_id: str
    status: Literal['running', 'completed', 'failed']
    turn: int
    max_turns: int
    random_seed: int
    end_reason: NotRequired[str | None]
    transcript: list[TranscriptTurn]
    sandbox: SandboxConfig
    tool_events: NotRequired[list[ToolCall]]


class RolloutTurnCreate(TypedDict):
    reply: NotRequired[str]
    tool_calls: NotRequired[list[ToolCall]]
    audio_b64: NotRequired[str | None]


class RunList(TypedDict):
    sessions: list[SdkSessionSummary]
    runs: list[RunSummary]


class DemoSimulation(TypedDict):
    id: str
    demo_session_id: str
    scenario_id: str
    status: Literal['running', 'succeeded', 'failed']
    error: NotRequired[str | None]
    tiers: NotRequired[dict[str, DemoTierResult] | None]
